// apps/web/src/components/NightOrderSheet.tsx
import type { ScriptId } from "@org/types";
import { SCRIPTS, getFirstNightOrder, getOtherNightOrder } from "@org/types";
import { Button } from "@/components/ui/button";
import { CharacterIcon } from "./CharacterToken";

interface NightOrderSheetProps {
  characterIds: string[];
  script: ScriptId;
  onClose?: () => void;
}

export function NightOrderSheet({
  characterIds,
  script,
  onClose,
}: NightOrderSheetProps) {
  const scriptData = SCRIPTS[script];

  if (!scriptData) {
    return (
      <div className="flex-1 p-6 bg-background overflow-y-auto">
        {onClose && (
          <Button variant="outline" onClick={onClose} className="mb-6">
            ← Back to Grimoire
          </Button>
        )}
        <p>Unknown script</p>
      </div>
    );
  }

  // Get only the selected characters
  const selectedCharacters = scriptData.characters.filter((c) =>
    characterIds.includes(c.id)
  );

  const firstNight = getFirstNightOrder(selectedCharacters);
  const otherNights = getOtherNightOrder(selectedCharacters);
  
  // Characters without night actions (no firstNightOrder or otherNightOrder)
  const noNightAction = selectedCharacters.filter(
    (c) => c.firstNightOrder === undefined && c.otherNightOrder === undefined
  );

  const typeColors: Record<string, string> = {
    townsfolk: "border-l-blue-500",
    outsider: "border-l-cyan-500",
    minion: "border-l-orange-500",
    demon: "border-l-red-500",
  };

  return (
    <div className="flex-1 p-6 bg-background overflow-y-auto">
      {onClose && (
        <Button variant="outline" onClick={onClose} className="mb-6">
          ← Back to Grimoire
        </Button>
      )}

      <div className="flex flex-col gap-8">
        <section className="flex-1">
          <h2 className="text-xl mb-4 text-[#c9a227]">First Night</h2>
          {firstNight.length === 0 ? (
            <p className="text-muted-foreground italic">No characters wake on the first night</p>
          ) : (
            <ol className="list-none p-0 m-0 [counter-reset:night-order]">
              {firstNight.map((char, index) => (
                <li
                  key={char.id}
                  className={`flex flex-col gap-1 p-3 mb-2 bg-card rounded-md border-l-4 relative pl-8 ${typeColors[char.type] || ""}`}
                  style={{ counterIncrement: "night-order" }}
                >
                  <span className="absolute -left-8 w-6 h-6 bg-muted rounded-full flex items-center justify-center text-xs text-muted-foreground">
                    {index + 1}
                  </span>
                  <div className="flex items-center gap-2">
                    <CharacterIcon iconName={char.icon} className="text-foreground" size={18} />
                    <span className="font-semibold text-foreground">{char.name}</span>
                  </div>
                  <span className="text-sm text-muted-foreground">{char.ability}</span>
                </li>
              ))}
            </ol>
          )}
        </section>

        <section className="flex-1">
          <h2 className="text-xl mb-4 text-[#c9a227]">Other Nights</h2>
          {otherNights.length === 0 ? (
            <p className="text-muted-foreground italic">No characters wake on other nights</p>
          ) : (
            <ol className="list-none p-0 m-0 [counter-reset:night-order]">
              {otherNights.map((char, index) => (
                <li
                  key={char.id}
                  className={`flex flex-col gap-1 p-3 mb-2 bg-card rounded-md border-l-4 relative pl-8 ${typeColors[char.type] || ""}`}
                  style={{ counterIncrement: "night-order" }}
                >
                  <span className="absolute -left-8 w-6 h-6 bg-muted rounded-full flex items-center justify-center text-xs text-muted-foreground">
                    {index + 1}
                  </span>
                  <div className="flex items-center gap-2">
                    <CharacterIcon iconName={char.icon} className="text-foreground" size={18} />
                    <span className="font-semibold text-foreground">{char.name}</span>
                  </div>
                  <span className="text-sm text-muted-foreground">{char.ability}</span>
                </li>
              ))}
            </ol>
          )}
        </section>

        {noNightAction.length > 0 && (
          <section className="flex-1">
            <h2 className="text-xl mb-4 text-[#c9a227]">No Night Action</h2>
            <ul className="list-none p-0 m-0">
              {noNightAction.map((char) => (
                <li
                  key={char.id}
                  className={`flex flex-col gap-1 p-3 mb-2 bg-card rounded-md border-l-4 ${typeColors[char.type] || ""}`}
                >
                  <div className="flex items-center gap-2">
                    <CharacterIcon iconName={char.icon} className="text-foreground" size={18} />
                    <span className="font-semibold text-foreground">{char.name}</span>
                  </div>
                  <span className="text-sm text-muted-foreground">{char.ability}</span>
                </li>
              ))}
            </ul>
          </section>
        )}
      </div>
    </div>
  );
}

// src/lib/components/night-order-sheet.svelte
<script lang="ts">
	import type { Character } from '$lib/types/characters';
	import { CHARACTERS_BY_TYPE } from '$lib/botc-data/trouble-brewing.svelte';

	let { 
		characters,
		showAllRoles = false
	}: { 
		characters: Character[];
		showAllRoles?: boolean;
	} = $props();

	const typeColors: Record<string, string> = {
		townsfolk: 'text-blue-500',
		outsiders: 'text-cyan-500',
		minions: 'text-orange-500',
		demons: 'text-red-500',
	};

	// All characters from the script
	const allCharacters = $derived([
		...CHARACTERS_BY_TYPE.townsfolk,
		...CHARACTERS_BY_TYPE.outsiders,
		...CHARACTERS_BY_TYPE.minions,
		...CHARACTERS_BY_TYPE.demons,
	]);

	// Characters to display based on toggle
	const displayCharacters = $derived(showAllRoles ? allCharacters : characters);

	// Sort characters by firstNightOrder
	const firstNight = $derived(
		displayCharacters
			.filter((c) => c.firstNightOrder !== undefined)
			.sort((a, b) => (a.firstNightOrder || 0) - (b.firstNightOrder || 0))
	);

	// Sort characters by otherNightOrder
	const otherNights = $derived(
		displayCharacters
			.filter((c) => c.otherNightOrder !== undefined)
			.sort((a, b) => (a.otherNightOrder || 0) - (b.otherNightOrder || 0))
	);

	// Characters without night actions
	const noNightAction = $derived(
		displayCharacters.filter(
			(c) => c.firstNightOrder === undefined && c.otherNightOrder === undefined
		)
	);
</script>

<div class="flex flex-col bg-base-100">
	<!-- Scrollable content -->
	<div class="flex-1 p-6 overflow-y-auto min-h-0">
		<div class="flex flex-col gap-8">
			<section class="flex-1">
				<div class="divider">First Night</div>
				{#if firstNight.length === 0}
					<p class="text-base-content/70 italic">No characters wake on the first night</p>
				{:else}
					<ol class="list-none p-0 m-0 flex flex-col gap-2">
						{#each firstNight as char}
							{@const CharIcon = char.icon}
							<li class="card flex flex-row gap-3 bg-base-200 p-3">
								<CharIcon size={16} class="min-w-5 h-5 {typeColors[char.type] || ''}" />
								<div class="flex flex-1 flex-col">
									<h3 class="font-medium text-sm">{char.name}</h3>
									<p class="text-xs text-base-content/60 mt-1 line-clamp-3">{char.ability}</p>
								</div>
							</li>
						{/each}
					</ol>
				{/if}
			</section>

			<section class="flex-1">
				<div class="divider">Other Nights</div>
				{#if otherNights.length === 0}
					<p class="text-base-content/70 italic">No characters wake on other nights</p>
				{:else}
					<ol class="list-none p-0 m-0 flex flex-col gap-2">
						{#each otherNights as char}
							{@const CharIcon = char.icon}
							<li class="card flex flex-row gap-3 bg-base-200 p-3">
								<CharIcon size={16} class="min-w-5 h-5 {typeColors[char.type] || ''}" />
								<div class="flex flex-1 flex-col">
									<h3 class="font-medium text-sm">{char.name}</h3>
									<p class="text-xs text-base-content/60 mt-1 line-clamp-3">{char.ability}</p>
								</div>
							</li>
						{/each}
					</ol>
				{/if}
			</section>

			{#if noNightAction.length > 0}
				<section class="flex-1">
					<div class="divider">No Night Action</div>
					<ul class="list-none p-0 m-0 flex flex-col gap-2">
						{#each noNightAction as char}
							{@const CharIcon = char.icon}
							<li class="card flex flex-row gap-3 bg-base-200 p-3">
								<CharIcon size={16} class="min-w-5 h-5 {typeColors[char.type] || ''}" />
								<div class="flex flex-1 flex-col">
									<h3 class="font-medium text-sm">{char.name}</h3>
									<p class="text-xs text-base-content/60 mt-1 line-clamp-3">{char.ability}</p>
								</div>
							</li>
						{/each}
					</ul>
				</section>
			{/if}
		</div>
	</div>
</div>
